### ISSUE TITLE
Frontend der Website (Sprechblase, Farbe, Icon, "Botto Schreibt ..." schöner machen etc.)

### ISSUE THREAD

**Issue by susuenayat** [ID-Start-Winter22/chat-team12#30]
Möglicherweise eine Farbe, die gut zum Logo passt

**Comment by tarzilla** [comment]
# Webdesign Prototype erstellt!

![Website Design](https://user-images.githubusercontent.com/114647698/206862515-ec30e88f-6292-4340-911e-ad05678069df.png)

**Comment by Theogra** [comment]
sehr cool habe oben links noch unser Logo hinzugefügt :)

**Comment by tarzilla** [comment]
hab ich gesehen! @Theogra sieht cool aus danke

**Comment by Theogra** [comment]
habe übrigens auch ein paar Bären - Emojis zu den Antworten von Botto hinzugefügt

**Comment by tarzilla** [comment]
Leider schaffe ich es nicht rechtzeitig die Website zu gestalten. Würde diese Issue auf Sprint 2 verschieben :(

**Comment by Ashz22** [comment]
> Leider schaffe ich es nicht rechtzeitig die Website zu gestalten. Würde diese Issue auf Sprint 2 verschieben :(

alles gut, habe erfahren dass wir gar keine website machen müssen........... zumindest für sprint 1 steht nix von interface

**Comment by susuenayat** [comment]
habe jetzt nicht unser logo hinzugefügt, die font von der nav bar geändert und die Hintergrundfarbe damit das alles nicht so leer aussieht. aber frontend ist wie besprochen ein issue für sprint 2 !

**Comment by tarzilla** [comment]
@susuenayat Super Danke dir! Wir kriegen es auf jeden fall noch hin 👍

**Comment by susuenayat** [comment]
perfekt ich close dieses issue damit es nicht zu unübersichtlich wird und mach dann ein neues auf für sprint 2!
