### ISSUE TITLE
Custom Action coden, die nach stresslevel unterteilt

### ISSUE THREAD

**Issue by Ashz22** [ID-Start-Winter22/chat-team12#31]

**Comment by susuenayat** [comment]
ich bin grade dabei! update euch sobald sie läuft. momentan funktioniert sie, aber sie unterteilt noch nicht wirklich

**Comment by Ashz22** [comment]
@susuenayat  oh shit ich wusste nich dass du daran arbeitest, ich hab es jetzt mit stories gelöst

**Comment by susuenayat** [comment]
ich habe mich an einer action versucht, die aber dann doch verworfen, weil die nicht ganz so gut funktioniert hat und du mir dann glücklicherweise bereits gesagt hattest, dass du es anders lösen konntest.
