### ISSUE TITLE
Icon überarbeiten

### ISSUE THREAD

**Issue by susuenayat** [ID-Start-Winter22/chat-team12#32]
Cleaner machen, kleine Veränderungen

**Comment by susuenayat** [comment]
mit illustrator gearbeitet damit die Linien klarer werden. (Pfade benutzt)
Außerdem ein text branding erstellt! sagt mir gerne wie ihr es findet.
@Ashz22 @tarzilla @Theogra 
![botto](https://user-images.githubusercontent.com/117979602/207048251-2d748481-ff9f-4917-92c8-6d58ab41c0e3.png)
![bottoicon](https://user-images.githubusercontent.com/117979602/207048257-19bf230a-3a30-41da-a74d-deb2dc185b9e.png)
![bottotext](https://user-images.githubusercontent.com/117979602/207048261-9543d323-fa6e-4d08-a4f1-495905ebb199.png)

**Comment by tarzilla** [comment]
@susuenayat sieht sehr nice aus!
hast du die Illustrationen in höheren Auflösung? wär sehr hilfreich!

**Comment by tarzilla** [comment]
@susuenayat Viel Besser Danke!
