### ISSUE TITLE
name action fixen

### ISSUE THREAD

**Issue by Ashz22** [ID-Start-Winter22/chat-team12#33]

**Comment by Ashz22** [comment]
@susuenayat was genau soll da funktionieren? dass der name gespeichert wird und der bot sagt "hallo wie gehts [username]?
soweit funktionierts bei mir.

**Comment by tarzilla** [comment]
Bei mir funktioniert es auch!

**Comment by tarzilla** [comment]
# Paar probleme:

Bot wird durch Username Story verwirrt. Greet finde ich soll eine eigene story sein. dadurch vermindern wir, dass rasa verwirrt wird.

**Comment by susuenayat** [comment]
> # Paar probleme:
> Bot wird durch Username Story verwirrt. Greet finde ich soll eine eigene story sein. dadurch vermindern wir, dass rasa verwirrt wird.

@tarzilla kannst du dafür ein neues issue erstellen und diese hier closen, da sie schon erledigt ist? du kannst dein Kommentar hier auch in dem neuen issue zitieren! (siehe bild)
<img width="326" alt="Bildschirmfoto 2022-12-12 um 22 13 22" src="https://user-images.githubusercontent.com/117979602/207155945-0288d126-d751-4b33-b733-ab457c4d096f.png">
