### ISSUE TITLE
Recherchiert zu Übungen oder hilfsmitteln im internet und unterteilt sie nach stresslevel

### ISSUE THREAD

**Issue by Ashz22** [ID-Start-Winter22/chat-team12#38]

**Comment by susuenayat** [comment]
@Ashz22 und ich haben unsere Therapieunterlagen durchforstet. ich werde einige Übungen die ich für chatbot kompatibel halte ins wiki schreiben

**Comment by susuenayat** [comment]
Übungen sind drin! Für Sprint 1 denke ich genügend. @Theogra schaust du es dir bitte an?

**Comment by Theogra** [comment]
ja würde ich auch sagen ich lass dieses Issue aber noch für Sprint 2 offen

**Comment by tarzilla** [comment]
@Theogra finde ich so gut

**Comment by susuenayat** [comment]
alles klar ich füg das label hinzu

**Comment by susuenayat** [comment]
auch hierfür mache ich ein separates issue auf um den überblick nicht zu verlieren
