### ISSUE TITLE
Dialogerstellung

### ISSUE THREAD

**Issue by Ashz22** [ID-Start-Winter22/chat-team12#39]
Jeder erstellt mind 1-2 Dialoge auf papier/tablet

**Comment by Ashz22** [comment]
https://miro.com/app/board/uXjVP9u6yJQ=/?moveToWidget=3458764540672321077&cot=14

Dialog erstellt (bei mir ebenfalls bitte nicht auf design achten)

**Comment by tarzilla** [comment]
#Neuigkeiten bei Atemübung dialog

- Man kriegt nebenbei auch einen GIF zur Visualisierung bei der Atemübung

**Comment by susuenayat** [comment]
dialog erstellt und im letzten treffen vorgetragen. werde es später implementieren

**Comment by susuenayat** [comment]
> dialog erstellt und im letzten treffen vorgetragen. werde es später implementieren

mein 2. dialog kommt in sprint 2. vorerst nur indecisive von mir + Erweiterung und hinzufügen von examples etc bei bereits vorhandenen
