### ISSUE TITLE
Wiki für Sprint 1 fertigstellen

### ISSUE THREAD

**Issue by Theogra** [ID-Start-Winter22/chat-team12#40]

**Comment by Theogra** [comment]
habe Überschriften zur Wiki-Seite hinzugefügt + Aufgabenreihenfolge strukturiert :)

**Comment by susuenayat** [comment]
habe bisschen was zu sprint 1 hinzugefügt (Icon, Geschichte, Name, Tone-of-Voice). ist erstmal alles nur ein rough draft. Habe ausserdem die Icon&Design Spalte allgemein mit dem neuen logo aktualisiert und die Änderungen kurz beschrieben.

**Comment by Theogra** [comment]
habe das Wiki fertig gestellt @tarzilla könntest du schauen ob ich etwas vergessen habe ? :)

**Comment by tarzilla** [comment]
@Theogra bin grad dabei! :)

**Comment by tarzilla** [comment]
@Theogra Habe es nochmals verbessert! würde sagen dass es fertig ist. Gute Arbeit Leute 💯
