### ISSUE TITLE
Fehlermeldungen implementieren

### ISSUE THREAD

**Issue by Ashz22** [ID-Start-Winter22/chat-team12#45]

**Comment by tarzilla** [comment]
https://stackoverflow.com/questions/66264896/how-to-give-out-user-input-error-messages-in-rasa

Hey, das könnte für die fehlermeldung hilfreich sein!

**Comment by susuenayat** [comment]
danke dir, ich versuche es später mal gleich damit!

**Comment by susuenayat** [comment]
ist implementiert, gepusht und läuft. Hilfestellung https://rasa.com/docs/rasa/fallback-handoff/#fallbacks

@tarzilla bitte Reviewen!

**Comment by tarzilla** [comment]
@susuenayat ok super, ich pull das morgen und versuche es noch zu optimieren!
