### ISSUE TITLE
stories kürzen und umschreiben

### ISSUE THREAD

**Issue by Ashz22** [ID-Start-Winter22/chat-team12#47]
Stories sollten in sich geschlossen sein sodass sie sich nicht überschneiden
botto sollte als erstes grüßen

**Comment by Ashz22** [comment]
![image](https://user-images.githubusercontent.com/116884343/207464301-008f947e-1276-4588-ad7f-8400d0ed8fad.png)

https://miro.com/app/board/uXjVP9u6yJQ=/?moveToWidget=3458764541225186888&cot=14

**Comment by Ashz22** [comment]
gepusht und nach dem oberen diagramm neu geordnet, ihr könnt mal ausprobieren wenn ihr zeit habt obs bei euch auch klappt
tagge jetzt einfach mal @susuenayat für review

**Comment by Theogra** [comment]
hat bis jetzt alles geklappt :)
