### ISSUE TITLE
Fehlermeldung Fehler beheben

### ISSUE THREAD

**Issue by susuenayat** [ID-Start-Winter22/chat-team12#48]
Die Fehlermeldung spinnt manchmal und spuckt ein "Das ist schön" oder ein gif vor der message aus. Wäre super wenn da ALLE mal drüber schauen ob es bei euch genau so ist und ob ihr es beheben könnt. Ich arbeite auch schon daran!

**Comment by susuenayat** [comment]
ich hab nicht wirklich was gefixed, aber die Fehlermeldung geht wieder. wollt ihr es mal ausprobieren und mir Rückmeldung geben. ihr könnt einfach gibberish reinschreiben und dann solltet ihr die error message bekommen

**Comment by Ashz22** [comment]
@susuenayat kannst du hier mit reinschreiben wie genau du die fehlermeldung angegangen bist? sonst wirds schwierig sie zu fixen wenn wir nicht wissen was du gemacht hast
und ja bei mir spinnt sie auch total, kommt einfach nach fast jeder interaktion..

**Comment by Ashz22** [comment]
https://forum.rasa.com/t/about-utter-default/14597/2
maybe this might help?

**Comment by susuenayat** [comment]
habe es versucht zu fixen! sollte bereits auf den main gepusht sein, bitte testen und berichten! @Ashz22 würdest du da mal hinschauen?

**Comment by susuenayat** [comment]
ok es funktioniert immer noch nicht. ich bin weiter dran!

**Comment by susuenayat** [comment]
@tarzilla gehts jetzt bei dir?

**Comment by tarzilla** [comment]
@susuenayat Es funktioniert wenn Rasa absolut nicht versteht. Für jetzt find ich es gut, jedoch können wir es in naher Zukunft verfeinert 🥇
