### ISSUE TITLE
natural language flow

### ISSUE THREAD

**Issue by Ashz22** [ID-Start-Winter22/chat-team12#50]
mehr antwortmöglichkeiten unter bottos utter

**Comment by susuenayat** [comment]
ich habe einige Übungen zu bottos utter hinzugefügt. würde sie morgen pushen!

**Comment by tarzilla** [comment]
# Verscshiebung auf Sprint 2

Leider schaffen wir das nicht rechtzeitig :(

**Comment by susuenayat** [comment]
@tarzilla pull nochmal die aktuelle version, da steht bisschen mehr als in sprint 1 :)

**Comment by Ashz22** [comment]
Formulierungen überarbeitet

**Comment by Theogra** [comment]
ok würd weitergeführt durch das Issue ChitChat
