### ISSUE TITLE
Conversation Design Canvas und Worksheet

### ISSUE THREAD

**Issue by Theogra** [ID-Start-Winter22/chat-team12#52]

**Comment by Theogra** [comment]
habe den rest ausgefüllt

**Comment by Theogra** [comment]
@tarzilla könntest du schell drüber gehen und nochmal
 schauen ob es passt ? :)

**Comment by tarzilla** [comment]
@Theogra bin grad drüber gegangen und habe kleine änderungen gemacht. Hast es seht gut gemacht danke dir!
