### ISSUE TITLE
Frontend bearbeiten und Digitales Zuhause erstellen

### ISSUE THREAD

**Issue by susuenayat** [ID-Start-Winter22/chat-team12#54]
## Step 1

- Botto Maskottchen PNG einfügen

## Step 2

- Nav Bar und Logo richtig positionieren

## Step 3

- Details im Hintergrund hinzufügen
# 
Für alles weitere werden neue Issues aufgemacht würde ich sagen (Design der Nav Bar, Design des Chatfensters und Sprechblasen, etc)

**Comment by tarzilla** [comment]
@Theogra und Ich haben an das Frontend und digitales Zuhasue bearbeitet und aufs Wiki reingestellt! könnt ihr dies reviwewen? @susuenayat @Ashz22

**Comment by susuenayat** [comment]
habe es mir angeschaut und finde es echt super! gibt mir ein total wohliges Gefühl. @Ashz22 schaust du auch noch und closed dann?

**Comment by Ashz22** [comment]
Sieht super aus Leute
