### ISSUE TITLE
Weitere Übungen ins Wiki+Rasa übertragen

### ISSUE THREAD

**Issue by susuenayat** [ID-Start-Winter22/chat-team12#55]
Schaut euch doch gerne das Wiki an was für Übungen ihr da so findet und übertragt die so in die Files, wie ihr findet, dass sie am besten passen!

Erstellt dafür gerne neue Stories, wenns passt :)

**Comment by susuenayat** [comment]
habe einige Übungen ins wiki übertragen. soll als Dictionary dienen an dem man sich bei weiteren iterationen bedienen kann. @tarzilla magst du die nur ganz kurz überfliegen?

**Comment by tarzilla** [comment]
@susuenayat schön erweitert! danke dir
