### ISSUE TITLE
Miro Concept Testing

### ISSUE THREAD

**Issue by Theogra** [ID-Start-Winter22/chat-team12#57]

**Comment by Theogra** [comment]
hey habe zu dem concept testing auf Miro den Test mit meinen Bruder ausgewertet :)

**Comment by tarzilla** [comment]
@Theogra Hab ich gesehen, voll süss

**Comment by tarzilla** [comment]
meine sind nun auch online auf dem MiroBoard von Sprint 2

**Comment by susuenayat** [comment]
Hab da echt einige coole Erkenntnisse rauslesen können ! das Testing von @Ashz22 war auch super
