### ISSUE TITLE
CHITCHAT

### ISSUE THREAD

**Issue by susuenayat** [ID-Start-Winter22/chat-team12#59]
aus den user testings hat sich heraus gestellt, dass Botto zu wenig chitchat hat.

**Comment by susuenayat** [comment]
aufgabe an alle bitte chitchats implementieren, aber kommentiert doch davor bitte, was ihr machen wollt, damit wir keine Überschneidungen haben. 

Ich würde übernehmen, dass Botto auf mehrere Wie gehts Variationen reagiert.

**Comment by Ashz22** [comment]
ich habe bisschen sorge dass rasa noch mehr verwirrt wird wenn wir noch mehr storys einfügen

**Comment by Ashz22** [comment]
https://rasa.com/docs/rasa/chitchat-faqs/

hier steht eine erklärung wie man bei Rasa Chitchat bauen sollte!

**Comment by Ashz22** [comment]
@susuenayat hey ich glaub es is nicht so ne gute idee wenn jetzt jeder ne story macht, wenn alle einverstanden sind würd ich einfach das tutorial da durchgehen und etwas in dem sinne implementieren glaub das is vlt schlauer, was meinst du?

**Comment by susuenayat** [comment]
ok das klingt gut, die Option ist mir tatsächlich nicht in den sinn gekommen. meld dich doch gerne wenn du da Unterstützung brauchst

**Comment by Ashz22** [comment]
chitchat: bot fragen, wies ihm geht ist implementiert
falls ihr noch andere Ideen oder wünsche habt gerne einfach mir bescheid sagen
@susuenayat kannst du checken wenn du zeit hast?

**Comment by susuenayat** [comment]
habs grade gecheckt und bei mir gehts auch, danke nochmal , fand das chitchat doch wichtig für den flow
